### ISSUE TITLE
Information about azimuth?

### ISSUE THREAD

**Issue by zolointo** [mdsteele/azimuth#1]
Apologies for putting this in the Issues log. Not sure how else to get in touch with you.

Matt from metroidvanias.com here. I have no idea how to build your game, but have been dropping by every few months in hopes of there being a playable build of azimuth.

Would you mind getting in touch with me if you're still working on this? Would love to see screens/video if you have them.

**Comment by mdsteele** [comment]
Hi Matt, thanks for your interest!

I am definitely still working on Azimuth, though it's very much a nights-and-weekends, when-I-have-free-time sort of thing.  Based on my current rate of progress, I'm hoping to have it done by a year from now (I started on it a bit over two years ago), but we'll see, I guess.  (-:

The game should currently build on Mac OS X and on GNU/Linux (run `make` from the command line in the root directory of the repository to build, and then `make run` to start the game), as long as you have clang or gcc installed, as well an appropriate version of SDL (v1.2.15 works well) and OpenGL.  The game hasn't yet been ported to Windows, but it would probably be very easy to do so for someone familiar with Windows programming (SDL and OpenGL are already cross-platform, so there's very little to be ported), and I'm hoping to find someone to do that sometime before the game is completed.

Much of the game is still very rough or incomplete (plot, graphics, music, level design, etc), but the early parts are mostly playable.  I'd be happy to try to  take some representative screenshots for you; feel free to send me a note at mdsteele@alum.mit.edu and I can email them to you.

**Comment by zolointo** [comment]
Swell! Just sent you a message!

**Comment by andrewrk** [comment]
I recommend using [mxe](mxe.cc) to make the windows build. You can build a statically-linked windows .exe while sitting comfortably in your osx or linux machine, and it's totally painless. mxe already has SDL available for compiling against too.

**Comment by mdsteele** [comment]
Thanks!  I will check that out.
