### ISSUE TITLE
Stuck...

### ISSUE THREAD

**Issue by zapalagrzegorz** [mdsteele/azimuth#24]
Hello,

I loved the game Azimuth. My son plays it with my little support.
However, it became really frustrating when we cannot progress forward.

Could you give some tip to move forward?

We beated Oth space gun boss. Collected:
- dynamic armor,
and then:
- infrascanner
- retro thrusters 
- and tractor beam. 

One way to go is to overcome this difficult location pointed by the arrow where waves of force field keep pushing me away though tried some times. Is it the place that I should now go? 

Thanks a lot for your help.
![Zrzut ekranu z 2024-06-09 08-54-47](https://github.com/mdsteele/azimuth/assets/20630161/419d12b8-35d7-409e-8489-67627e4959a9)

**Comment by mdsteele** [comment]
Thanks for the message!  Always a pleasure to hear from people who are enjoying the game.  Sorry that you got stuck.

No, the forcefield room that the green arrow is pointing to is not where you want to go right now.  It's intended to be a one-way path that you can only traverse from bottom to top.

Instead, I believe you want to follow the red arrow path I've marked below.  That will lead you to a new upgrade that will allow you to pass through the obstacle marked with the yellow circle.  From there you'll be able to work your way towards the next boss.

Hope that helps.  Let me know if not, or if you get stuck again.

![azimuth-map](https://github.com/mdsteele/azimuth/assets/35096/c6d473fa-164c-47e7-b740-132a8514a6e4)

**Comment by zapalagrzegorz** [comment]
Omg. It was just a normal path, nothing to solve. And we've wandered half of the current map! It's a great relief to solve this. Many thanks.
I think there should be a button 'buy me a coffee', to praise good work.
