### ISSUE TITLE
Compilation fails on Debian Buster

### ISSUE THREAD

**Issue by genpfault** [mdsteele/azimuth#5]
Trying to build the current `master` (89f9b48c8a) on Debian Buster, amd64.

GCC version info:

```
$ gcc --version
gcc (Debian 8.2.0-16) 8.2.0
```

Error:

```
src/editor/audit.c: In function ‘az_audit_scenario’:
src/editor/audit.c:150:10: error: ‘console_kind’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
       if (console_kind == AZ_CONS_SAVE) {
          ^
```

Setting `console_kind` to `AZ_NODE_NOTHING` on `audit.c:146` fixes it for me.

**Comment by Domosed-gamin** [comment]
I have this problem too. Pls fix it. Game looks great.

**Comment by andrewrk** [comment]
I can confirm, the game is great. If you're a Debian maintainer, you can add a patch with this fix to your package. If you're just trying to play the game, you can apply the fix that @genpfault suggested. I'm not sure who is left, it seems like everyone here is taken care of to me!

**Comment by Domosed-gamin** [comment]
**andrewrk** 

> Setting console_kind to AZ_NODE_NOTHING on audit.c:146 fixes it for me.

How I can make it? I'm linux nab.

**Comment by andrewrk** [comment]
1. You'll need to use a text editor to open the file src/editor/audit.c.
2. Look for line number 146. Depending on what text editor you use, this will be very easy or very time consuming.
3. The line says `az_console_kind_t console_kind;` as per @genpfault's suggestion, you'll want to change this line to `az_console_kind_t console_kind = AZ_NODE_NOTHING;`
4. Save the file, and then go back to the build instructions from the README.

**Comment by Domosed-gamin** [comment]
**andrewrk**

Big thanks, man. It work for me.

**Comment by mdsteele** [comment]
Thanks for the report!  Looks like the compiler is being a bit over-cautious here, since that function only reads `console_kind` if `num_consoles` is nonzero, and `count_consoles()` always sets `console_kind` when it returns a nonzero value.  But it's harmless to initialize `console_kind` before calling `count_consoles()`, so may as well make the compiler happy.  (-:  Fix incoming.
