### ISSUE TITLE
An install target for make

### ISSUE THREAD

**Issue by marius851000** [mdsteele/azimuth#6]
Hello. I recently packaged your game for the nix package manager (https://github.com/NixOS/nixpkgs/pull/59071), and I think it'll be interesing to add an install target. The one I made is : 

    mkdir -p $out/bin
    cp out/release/host/bin/azimuth $out/bin/azimuth
    cp out/release/host/bin/editor $out/bin/azimuth-editor
    cp out/release/host/bin/muse $out/bin/azimuth-muse
    cp out/release/host/bin/zfxr $out/bin/azimuth-zfxr
    mkdir -p $out/share/doc/azimuth
    cp doc/* README.md LICENSE $out/share/doc/azimuth
    mkdir -p $out/share/icons/hicolor/128x128/apps $out/share/icons/hicolor/64x64/apps $out/share/icons/hicolor/48x48/apps $out/share/icons/hicolor/32x32/apps
    cp data/icons/icon_128x128.png $out/share/icons/hicolor/128x128/apps/azimuth.png
    cp data/icons/icon_64x64.png $out/share/icons/hicolor/64x64/apps/azimuth.png
    cp data/icons/icon_48x48.png $out/share/icons/hicolor/48x48/apps/azimuth.png
    cp data/icons/icon_32x32.png $out/share/icons/hicolor/32x32/apps/azimuth.png
    mkdir -p $out/share/applications
    cp data/azimuth.desktop $out/share/applications

and

    substituteInPlace data/azimuth.desktop \
      --replace Exec=azimuth "Exec=$out/bin/azimuth" \
      --replace "Version=%AZ_VERSION_NUMBER" "Version=${version}"

**Comment by mdsteele** [comment]
Very cool!  Do you have a pull request for the necessary changes to the Makefile?

By the way, note that the `editor`, `muse`, and `zfxr` binaries were just some hacky development tools I used while writing the game, and are unnecessary for actually playing it.  So there's no real need to install those.

**Comment by mdsteele** [comment]
Fixed by #7.
